###
GET http://localhost:3001/users/


###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "nom": "John Doe",
  "email": "johndoe@example.com",
  "password": "newpassword",
  "role": "ADMIN"
}


###

DELETE http://localhost:3001/users/12

###

POST http://localhost:3001/users
Content-Type: application/json

{
  "nom": "John Doe",
  "email": "jhndoe@example.com",
  "password": "password1234",
  "role": "AUTHOR"
}
